### ISSUE TITLE
1.1QP2-1.19.4 broken pack.mcmeta

### ISSUE THREAD

**Issue by W2D3F1X2** [TsaiTou2926/Ingoted-Ores#1]
In pack.mcmeta of Ingoted Ores 1.1QP2-1.19.4 a quotation mark is missing so the pack doesn't work.

**Comment by Tsaitou7361** [comment]
sorry for late because there was no notification.
But we have been updated to 2.0Q.
If you still have any problem, you can open another issue for me.
Thanks for your report.
Expect your #2 issue of this project.
